// Auto-generated by ClipToEnumGenerator

namespace Racer.EzSoundCore.Samples
{
    public enum ClipId
    {
        _110215__cheesepuff__a_soothing_song_Tweak,
        _131660__bertrof__game_sound_correct,
        _448081__breviceps__tic_toc_click,
    }
}